export const ACTIONS = {
    CHECK_IS_WORK: 'CHECK_IS_WORK',
    ADD_EDGE: 'ADD_EDGE',
    TOGGLE_NODES_IN_FALSE: 'TOGGLE_NODES_IN_FALSE',
    CLICKED_NODE: "CLICKED_NODE",
    SEND_NAME: 'SEND_NAME'
    
  };